import fs from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { beatTrack } from "@audio/beat";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const audioPath = path.join(root, "public", "audio", "Please tell me why.mp3");
const outputPath = path.join(root, "game", "generated-rhythm.ts");
const SAMPLE_RATE = 22050;
const FALLBACK_BPM = 80;
const FALLBACK_BEATS = 512;

function decodeWithFfmpeg(inputPath) {
  return new Promise((resolve, reject) => {
    const child = spawn("ffmpeg", [
      "-hide_banner",
      "-loglevel", "error",
      "-i", inputPath,
      "-f", "f32le",
      "-ac", "1",
      "-ar", String(SAMPLE_RATE),
      "pipe:1",
    ]);
    const chunks = [];
    const errors = [];
    child.stdout.on("data", (chunk) => chunks.push(chunk));
    child.stderr.on("data", (chunk) => errors.push(chunk));
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(Buffer.concat(errors).toString("utf8") || `ffmpeg exited with ${code}`));
        return;
      }
      const pcm = Buffer.concat(chunks);
      if (pcm.byteLength < 16) {
        reject(new Error("ffmpeg returned no PCM audio"));
        return;
      }
      resolve(new Float32Array(pcm.buffer, pcm.byteOffset, Math.floor(pcm.byteLength / 4)));
    });
  });
}

function fallbackBeatGrid() {
  return Array.from({ length: FALLBACK_BEATS }, (_, index) => (index * 60000) / FALLBACK_BPM);
}

try {
  await fs.access(audioPath);
  const mono = await decodeWithFfmpeg(audioPath);
  const tracked = beatTrack(mono, {
    fs: SAMPLE_RATE,
    bpm: FALLBACK_BPM,
    minBpm: 70,
    maxBpm: 100,
    tightness: 680,
  });
  const beatsMs = Array.from(tracked.beats, (seconds) => Number((seconds * 1000).toFixed(3)));
  const bpm = Number.isFinite(tracked.bpm) && tracked.bpm > 0 ? Number(tracked.bpm.toFixed(3)) : FALLBACK_BPM;
  const confidence = Number.isFinite(tracked.confidence) ? Number(tracked.confidence.toFixed(4)) : 0;

  if (beatsMs.length < 16) throw new Error(`Beat tracker returned only ${beatsMs.length} beats`);

  await fs.writeFile(
    outputPath,
    `// Generated by scripts/analyze-rhythm.mjs. Do not edit manually.\nexport const ANALYZED_BPM = ${bpm};\nexport const ANALYZED_CONFIDENCE = ${confidence};\nexport const ANALYZED_BEATS_MS = ${JSON.stringify(beatsMs)} as const;\n`,
  );
  console.log(`[rhythm-analysis] BPM=${bpm} confidence=${confidence} beats=${beatsMs.length}`);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.warn(`[rhythm-analysis] INVALID/UNREADABLE AUDIO — using ${FALLBACK_BPM} BPM fallback: ${message}`);
  const beatsMs = fallbackBeatGrid();
  await fs.writeFile(
    outputPath,
    `// Generated by scripts/analyze-rhythm.mjs. Do not edit manually.\nexport const ANALYZED_BPM = ${FALLBACK_BPM};\nexport const ANALYZED_CONFIDENCE = 0;\nexport const ANALYZED_BEATS_MS = ${JSON.stringify(beatsMs)} as const;\n`,
  );
}
