import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import decode from "audio-decode";
import { beatTrack } from "@audio/beat";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const audioPath = path.join(root, "public", "audio", "Please tell me why.mp3");
const outputPath = path.join(root, "game", "generated-rhythm.ts");
const FALLBACK_BPM = 80;

function mixToMono(channelData) {
  if (channelData.length === 1) return channelData[0];
  const length = channelData[0]?.length ?? 0;
  const mono = new Float32Array(length);
  for (const channel of channelData) {
    for (let index = 0; index < length; index += 1) mono[index] += channel[index] / channelData.length;
  }
  return mono;
}

function fallbackBeatGrid(durationSeconds) {
  const beatCount = Math.max(1, Math.floor(durationSeconds * FALLBACK_BPM / 60));
  return Array.from({ length: beatCount }, (_, index) => (index * 60000) / FALLBACK_BPM);
}

try {
  const bytes = await fs.readFile(audioPath);
  const decoded = await decode(bytes);
  const mono = mixToMono(decoded.channelData);
  const tracked = beatTrack(mono, {
    fs: decoded.sampleRate,
    bpm: FALLBACK_BPM,
    minBpm: 70,
    maxBpm: 100,
    tightness: 680,
  });
  const beatsMs = Array.from(tracked.beats, (seconds) => Number((seconds * 1000).toFixed(3)));
  const bpm = Number.isFinite(tracked.bpm) && tracked.bpm > 0 ? Number(tracked.bpm.toFixed(3)) : FALLBACK_BPM;
  const confidence = Number.isFinite(tracked.confidence) ? Number(tracked.confidence.toFixed(4)) : 0;

  if (beatsMs.length < 16) throw new Error(`Beat tracker returned only ${beatsMs.length} beats`);

  await fs.writeFile(
    outputPath,
    `// Generated by scripts/analyze-rhythm.mjs. Do not edit manually.\nexport const ANALYZED_BPM = ${bpm};\nexport const ANALYZED_CONFIDENCE = ${confidence};\nexport const ANALYZED_BEATS_MS = ${JSON.stringify(beatsMs)} as const;\n`,
  );
  console.log(`[rhythm-analysis] BPM=${bpm} confidence=${confidence} beats=${beatsMs.length}`);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.warn(`[rhythm-analysis] analysis failed, using ${FALLBACK_BPM} BPM fallback: ${message}`);
  const stats = await fs.stat(audioPath);
  const durationSeconds = Math.max(1, stats.size / 16000);
  const beatsMs = fallbackBeatGrid(durationSeconds);
  await fs.writeFile(
    outputPath,
    `// Generated by scripts/analyze-rhythm.mjs. Do not edit manually.\nexport const ANALYZED_BPM = ${FALLBACK_BPM};\nexport const ANALYZED_CONFIDENCE = 0;\nexport const ANALYZED_BEATS_MS = ${JSON.stringify(beatsMs)} as const;\n`,
  );
}
